service: covid19-lga-arcgis-au # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2
  timeout: 60 # optional, in seconds, default is 6
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "*"

functions:
  app:
    handler: index.handler
    timeout: 60 # optional, in seconds, default is 6
    events:
      - schedule:
        rate: rate(3 hour)
plugins:
  - serverless-offline
